server:
  port: 8005
spring:
  profiles:
      active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/flag?useUnicode=true&amp;characterEncoding=UTF-8
    username: flag
    password: flag

jwt:
  http:
    header: Authorization
  idKey: userId
  roleKey: role
  secret: flag
  expireTime: 2592000000 # 30day

---
spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "[%-5level] %d{yyyy-MM-dd HH:mm:ss} [%thread] %logger{36} - %msg%n"
  file: /www/wwwlogs/flagadmin.log
  level:
    root: warn
    org.springframe.web: warn
    com.ctg: warn

---
spring:
  profiles: pro
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
logging:
  level:
    root: error
    org.springframework.web: error
    com.ctg: error
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "[%-5level] %d{yyyy-MM-dd HH:mm:ss} [%thread] %logger{36} - %msg%n"
  file: /www/wwwlogs/flagadmin.log
